### ISSUE TITLE
i can't access to the javadoc 

### ISSUE THREAD

**Issue by thewrath** [pdinklag/JSFML#68]
Hello, i use Jsfml for my school project and i can't access to the javadoc because i think you have stop the dev of your lib. can you send me a copy of the javadoc if it's possible thank you. 
Sorry but i'm french and my english is poor

**Comment by mantognini** [comment]
There should be an ant target to build the javadoc. Have you tried that?

**Comment by pdinklag** [comment]
Indeed, you can build the javadoc from the source with the respective ant target.

My webserver seems to have some occasional trouble since I updated the server to Debian 8. Sadly, I don't know the cause yet, but despite the fact that I stopped working on JSFML, I have no plans to take down the website!

**Comment by pdinklag** [comment]
As you may have noticed, I did not renew the `jsml.org` domain because I abandoned this project.
The website has thankfully been archived here: https://jsfml.sfmlprojects.org/
